export const AppColors ={
    Blcak_Color:'#000',
    White_Color:'#FDFEFF',
    BaliHai_Color:'#8C9CAB',
    AliceBlue_Color:'#EDF2F7',
    AliceBlue_Bg:"#F9FBFC",
    Mustard_Color:'#FFD953',
    Tomato_Color:'#FF5656',
    PattenseBlue_Color:'#D4DEE7',
    Matterhorn_Color:'#4F4F4F',
    Charcoal_Color:'#444444',
    Eclipse_Color:'#404040',
    GoldenTainoi_Color:'#FFC24B',
    SweetCorn_Color:'#FFDF6C',
    Solitude_Color:'#E7EEF5',
    Heather_Color:'#B1BAC3',
    PattensBlue_Color:'#D3DEE7',
    NeonBlue_Color:'#4541F3'
}