export const t = (lang = 'ru') => {
    if (lang == 'en') {
        return {
            Editprofile: "Edit profile",
            EditPost: "Edit post",
            Contacts: "Contacts",
            Edit: "Edit",
            Deletepost: "Delete post",
            Subscriptions: 'Subscriptions',
            Recommendations: "Recommendations",
            Selectacategory: 'Select a category',
            search: "Search",
            Catalog: "Headings",
            Notfound: "Not found",
            subscribe: "subscribe",
            Unsubscribe: "Unsubscribe",
            Youhavenomessages: "You have no messages",
            Newpublication: "New publication",
            adddescription: "Add description in photo ",
            Addphoto: "Add photo/video",
            noPublications: "no publications",
            Bookmarklistisempty: 'Bookmark list is empty',
            Listlistisempty: 'empty tape',
            Album: 'Album',
            ChangePhoto: 'Change photo',
            Information: 'Information',
            Musicfromthevideo: "Music from the video (in the presence of)",
            changelanguage: "Language change",
            Choosecatalog: 'Which category should I add it to?',
            Yourcontent: 'Your content will reach the recipient exactly and will be seen by those people who subscribe to this section',
            Publications: 'Publications',
            Subscribers: 'Subscribers',
            Nosubscribers: 'No subscribers',
            Nosubscriptions: 'No subscriptions',
            Bookmarks: 'Bookmarks',
            logOut: 'Log Out',
            Blacklist: 'Black list',
            Accountsettings: 'Account settings',
            Addinformation: "Add. information",
            City: 'City',
            DateofBirth: 'Date of Birth',
            gender: 'gender',
            ProfessionFieldofactivity: "Profession/Field of activity",
            Placeofwork: "Place of work",
            Website: 'Website',
            Mail: 'Mail',
            Phonenumber: 'Phone number',
            Brieflyaboutyourself: 'Briefly about yourself',
            Day: 'Day',
            Confirmpassword: "Confirm password",
            Month: 'Month',
            Year: 'Year',
            Male: 'Male',
            Female: 'Female',
            Changepassword: 'Change password',
            Changemail: 'Change mail',
            OldPassword: 'Old Password',
            NewPassword: "New Password",
            repeatnewpassword: 'Repeat new password',
            Confirm: 'Confirm',
            password: 'Password',
            intoablacklist: 'into a black list',
            Blacklistisempty: "Blacklist is empty",
            Login: 'Login',
            Enteryouremail: 'Enter your email',
            enterpassword: 'Enter password',
            Forgotpassword: 'Forgot password?',
            Registration: 'Registration',
            Savepassword: 'Save password',
            Createapassword: 'Create a password',
            Repeatpassword: 'Repeat password',
            Passwordrecovery: 'Password recovery',
            Enteremailmail: 'Enter email',
            Next: 'Next',
            Comeupwithanicknam: 'Come up with a nickname',
            Enteryouremail: 'Enter your email',
            FirstnameLastnameorchannelname: 'First name Last name or channel name',
            Companyname: 'Company name',
            comments: 'Comments',
            Nocomments: 'No comments',
            Leaveacomment: 'Leave a comment',
            Women: 'Women',
            Men: "Men",
            Unspecifiedgender: 'Unspecified gender',
            AboutProgram: "Who we are",
        }
    }
    {
        return {
            Editprofile: "Редактировать профиль",
            EditPost: "Редактировать пост",
            Contacts: "Контакты",
            Edit: "Редактировать",
            Confirmpassword: "Подтвердите пароль",
            Deletepost: "Удалить пост",
            Companyname: 'Название компании',
            search: "Поиск",
            Notfound: "Не найдено",
            subscribe: "Подписаться",
            Unsubscribe: "Отписаться",
            Youhavenomessages: "У вас нет сообщений",
            Newpublication: "Новая публикация",
            adddescription: "Добавить описание",
            Musicfromthevideo: "Музыка из видео (при наличии)",
            Addphoto: "Добавить фото/видео",
            noPublications: "нет публикаций",
            Bookmarklistisempty: 'Список закладок пуст',
            Album: 'Альбом',
            Listlistisempty: 'Пустая лента',
            Subscriptions: 'Подписки',
            Recommendations: "Попутный контент",
            Choosecatalog: 'В какую рубрику выложить?',
            Information: 'Информация',
            Publications: 'Публикации',
            Subscribers: 'Подписчики',
            Nosubscribers: 'Нет подписчиков',
            Nosubscriptions: 'Нет подписок',
            Bookmarks: 'Закладки',
            logOut: 'Выйти',
            Blacklist: 'Черный список',
            Accountsettings: 'Параметры аккаунта',
            Addinformation: "Доп. информация",
            City: 'Город',
            DateofBirth: 'Дата рождения',
            gender: 'Пол',
            ProfessionFieldofactivity: "Профессия/должность",
            Placeofwork: "Место работы",
            Website: 'Сайт',
            Mail: 'Почта',
            Phonenumber: 'Phone number',
            changelanguage: "Изменение языка",
            Brieflyaboutyourself: 'Кратко о себе',
            Day: 'День',
            Month: 'Месяц',
            Year: 'Год',
            Male: 'Мужской',
            Female: 'Женский',
            Changepassword: 'Изменить пароль',
            Changemail: 'Изменить почту',
            ChangePhoto: 'Изменить фото',
            Catalog: "Рубрики",
            OldPassword: 'Старый пароль',
            NewPassword: "Новый пароль",
            repeatnewpassword: 'Повторите новый пароль',
            Confirm: 'Подтвердить',
            password: 'Пароль',
            intoablacklist: 'В черный список',
            Blacklistisempty: "Черный список пуст",
            Yourcontent: '(Ваш контент дойдет точно до адресата, и увидят те люди,  кто не обязательно подписан на Вас, но выбрали данную рубрику.)',
            Selectacategory: 'выберите рубрику',
            Login: 'Вход',
            Enteryouremail: 'Введите е-майл',
            enterpassword: 'Введите пароль',
            Forgotpassword: 'Забыли пароль?',
            Registration: 'Регистрация',
            Savepassword: 'Сохранить пароль',
            Createapassword: 'Придумайте пароль',
            Repeatpassword: 'Повторите пароль',
            Passwordrecovery: 'Восстановление пароля',
            Enteremailmail: 'Введите эл. почту',
            Next: 'Далее',
            Comeupwithanicknam: 'Придумайте никнейм',
            Enteryouremail: 'Укажите почту',
            FirstnameLastnameorchannelname: 'Имя Фамилия или название канала',
            comments: 'Комментарии',
            Nocomments: ' Нет комментариев',
            Leaveacomment: 'Оставьте комментарий',
            Women: 'Женщины',
            Men: "Mужчины",
            Unspecifiedgender: 'Неуказанные гендере',
            AboutProgram: "Кто мы?",
        }
    }
}
